import mongoose from 'mongoose'

const storeSchema = new mongoose.Schema({
  'package.json': String,
  'readme.md': String,
  frontend: {
    'package.json': String,
    public: {
      'index.html': String,
    },
    src: {
      'index.css': String,
      'index.js': String,
      'userChoices.json': {
        owner_name: String,
        owner_email: String,
        title: String,
        landingPage: String,
        selectedBootstrap: String,
        selectedBootstrap_File: String,
        MONGODB_URI: String,
        includeProductListScreen: Boolean,
        productListScreen: {
          navbar: Boolean,
          footer: Boolean,
          rodape: String,
          color: String,
          tamanhoimagem: String,
        },
        includeAuthPages: Boolean,
        authPages: {
          registerScreenFile: String,
          loginScreenFile: String,
          userConstantsFile: String,
          userActionsFile: String,
          userReducersFile: String,
          userRoutesFile: String,
          userControllerFile: String,
          orderReducersFile: String,
          orderConstantsFile: String,
          showAppBarInRegister: Boolean,
          showAppBarInLogin: Boolean,
          showCartIcon: Boolean,
          JWT_SECRET: String,
        },
        includeHomeScreen: Boolean,
        homeScreen: {
          homeScreenFile: String,
          productScreenFile: String,
          productComponentFile: String,
          ratingFile: String,
          filterCardFile: String,
          showAppBarInHome: Boolean,
          homeTitle: String,
          homeMessage: String,
        },
        includeShopCart: Boolean,
        cartScreen: {
          showAppBarInCart: Boolean,
          showCartIcon: Boolean,
          cartMessage: String,
        },
        includePlaceOrder: Boolean,
        placeOrderScreens: {
          orderControllerFile: String,
          orderRoutesFile: String,
          placeOrderSceenFile: String,
          shippingScreenFile: String,
          selectPaymentScreenFile: String,
          orderScreenFile: String,
          checkoutStepsCompFile: String,
          orderActionsFile: String,
          showAppBarInPlaceOrder: Boolean,
          PAYPAL_CLIENT_ID: String,
        },
      },
      'bootstrap.min.css': String,
      'App.js': String,
      'store.js': String,
      components: {
        'Footer.js': String,
        'Header.js': String,
        'SearchBox.js': String,
        'Message.js': String,
        'CustomMessage.js': String,
        'CustomSpinner.js': String,
        'useHome.js': String,
        'FormContainer.js': String,
        'Loader.js': String,
        'Product.js': String,
        'Rating.js': String,
        'FilterCard.js': String,
        'CheckoutSteps.js': String,
      },
      actions: {
        'productActions.js': String,
        'categoryActions.js': String,
        'cartActions.js': String,
        'userActions.js': String,
        'orderActions.js': String,
      },
      reducers: {
        'productReducers.js': String,
        'categoryReducers.js': String,
        'cartReducers.js': String,
        'userReducers.js': String,
        'orderReducers.js': String,
      },
      constants: {
        'productConstants.js': String,
        'categoryConstants.js': String,
        'cartConstants.js': String,
        'userConstants.js': String,
        'orderConstants.js': String,
      },
      screens: {
        'ProductEditScreen.js': String,
        'ProductListScreen.js': String,
        'CategoriesList.js': String,
        'HomeScreen.js': String,
        'ProductScreen.js': String,
        'CartScreen.js': String,
        'LoginScreen.js': String,
        'RegisterScreen.js': String,
        'PlaceOrderScreen.js': String,
        'ShippingScreen.js': String,
        'SelectPaymentScreen.js': String,
        'OrderScreen.js': String,
      },
    },
  },
  backend: {
    'server.js': String,
    utils: {
      'generateToken.js': String,
    },
    models: {
      'productModel.js': String,
      'userModel.js': String,
      'orderModel.js': String,
    },
    middleware: {
      'authMiddleware.js': String,
      'errorMiddleware.js': String,
    },
    controllers: {
      'userController.js': String,
      'orderController.js': String,
    },
    routes: {
      'userRoutes.js': String,
      'orderRoutes.js': String,
    },
    config: {
      'db.js': String,
    },
    produtos: {
      'productModel.js': String,
      'productController.js': String,
      'uploadRoutes.js': String,
      'productRoutes.js': String,
    },
    categorias: {
      'categoryController.js': String,
      'categoryRoutes.js': String,
      'categoryModel.js': String,
    },
    cms: {
      'cmsModel.js': String,
      'cmsRoutes.js': String,
      'cmsController.js': String,
    },
  },
})

const StoreModel = mongoose.model('stores', storeSchema)
export default StoreModel
