export const INSERT_USER_CHOICES_REQUEST = 'INSERT_USER_CHOICES_REQUEST'
export const INSERT_USER_CHOICES_SUCCESS = 'INSERT_USER_CHOICES_SUCCESS'
export const INSERT_USER_CHOICES_FAILURE = 'INSERT_USER_CHOICES_FAILURE'

export const GET_ALL_USER_CHOICES_REQUEST = 'GET_ALL_USER_CHOICES_REQUEST'
export const GET_ALL_USER_CHOICES_SUCCESS = 'GET_ALL_USER_CHOICES_SUCCESS'
export const GET_ALL_USER_CHOICES_FAILURE = 'GET_ALL_USER_CHOICES_FAILURE'
export const GET_ALL_USER_CHOICES_RESET = 'GET_ALL_USER_CHOICES_RESET'

export const STORE_DETAILS_REQUEST = 'STORE_DETAILS_REQUEST'
export const STORE_DETAILS_SUCCESS = 'STORE_DETAILS_SUCCESS'
export const STORE_DETAILS_FAIL = 'STORE_DETAILS_FAIL'
export const STORE_DETAILS_RESET = 'STORE_DETAILS_RESET'

export const STORE_UPDATE_REQUEST = 'STORE_UPDATE_REQUEST'
export const STORE_UPDATE_SUCCESS = 'STORE_UPDATE_SUCCESS'
export const STORE_UPDATE_FAIL = 'STORE_UPDATE_FAIL'
export const STORE_UPDATE_RESET = 'STORE_UPDATE_RESET'
